export enum City {
  SEOUL = 'Seoul',
  BUSAN = 'Busan',
  INCHEON = 'Incheon',
  DAEGU = 'Daegu',
  DAEJEON = 'Daejeon',
  GWANGJU = 'Gwangju',
  ULSAN = 'Ulsan',
  GANGWON = 'Gangwon',
  CHUNGBOK = 'Chungbuk',
  CHUNGNAM = 'Chungnam',
  JEONBUK = 'Jeonbuk',
  JEONNAM = 'Jeonnam',
  GYEONGBUK = 'Gyeongbuk',
  GYEONGNAM = 'Gyeongnam',
  JEJU = 'Jeju',
  GYEONGGI = 'Gyeonggi',
}
